// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Play.User.Service.Data;

#nullable disable

namespace Play.User.Service.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129210752_Create-Database")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Play.User.Service.Entities.MessageIds", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("MessageIds");
                });

            modelBuilder.Entity("Play.User.Service.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("firstname");

                    b.Property<decimal>("Gil")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("gil");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("lastname");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Play.User.Service.Entities.MessageIds", b =>
                {
                    b.HasOne("Play.User.Service.Entities.User", "User")
                        .WithMany("MessageIds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Play.User.Service.Entities.User", b =>
                {
                    b.Navigation("MessageIds");
                });
#pragma warning restore 612, 618
        }
    }
}
